defmodule ElixirScript.Web.Math do
  use ElixirScript.FFI, global: true, name: :Math

  #Properties
  #TODO: Capitals :(

  #Methods
  defexternal abs(x)
  defexternal acos(x)
  defexternal acosh(x)
  defexternal asin(x)
  defexternal asinh(x)
  defexternal atan(x)
  defexternal atanh(x)
  defexternal atan2(y, x)
  defexternal cbrt(x)
  defexternal ceil(x)
  defexternal clz32(x)
  defexternal cos(x)
  defexternal cosh(x)
  defexternal exp(x)
  defexternal expm1(x)
  defexternal floor(x)
  defexternal fround(x)
  defexternal hypot(x)
  defexternal hypot(x, y)
  defexternal hypot(x, y, z)
  defexternal imul(x, y)
  defexternal log(x)
  defexternal log1p(x)
  defexternal log10(x)
  defexternal log2(x)
  defexternal max(x)
  defexternal max(x, x1)
  defexternal max(x, x1, x2)
  defexternal min(x)
  defexternal min(x, x1)
  defexternal min(x, x1, x2)
  defexternal pow(x, y)
  defexternal random()
  defexternal round(x)
  defexternal sign(x)
  defexternal sin(x)
  defexternal sinh(x)
  defexternal sqrt(x)
  defexternal tan(x)
  defexternal tanh(x)
  defexternal trunc(x)
end
